package com.anil.awslambda.model;


import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.Data;

@DynamoDBTable(tableName = "state")
@Data
public class State {

	@DynamoDBHashKey(attributeName = "stateId")
	@DynamoDBAutoGeneratedKey
	private String stateId;
	@DynamoDBAttribute(attributeName = "stateName")
	private String stateName;
}
